### ISSUE TITLE
Add functionality to conveniently get the content of a Trendmark as string

### ISSUE THREAD

**Issue by gemdav** [FraunhoferISST/Innamark#107]
# 🚀 Feature Request

## Current Problem

Currently, it is particularly hard to get the content of a Trendmark as a string. While the byte array content can be parsed to a string by the target library (theoretically), this is not so easy when e.g. creating a Javascript application that is executed in multiple different environment, as the tools to perform this action depend on the environment at hand.

## Proposed Solution

The easiest (and probably also most convient) solution would be to have a function in the TREND library that gives me the content of a Trendmark as a string directly.

**Comment by mhellmeier** [comment]
I understand the problem you are facing. However, I think it isn't a "real" problem that something doesn't work. It is more of a whish for easier use without conversion by the user of the TREND library.

Regarding your proposed solution:
> The easiest (and probably also most convient) solution would be to have a function in the TREND library that gives me the content of a Trendmark as a string directly.

When preparing implementation suggestions, remember that it is also possible to use the TREND library to watermark a custom Byte sequence inside a cover that is not in the format of a String. On the one hand, one can argue against including this functionality inside the core library since it is related to a specific use case (String watermarking). On the other hand, the majority of users use the String format, where such a helper function makes sense.

Therefore, error handling and remembering cases where Strings aren't used need to be remembered when preparing a pull request for this issue.

**Comment by gemdav** [comment]
@mhellmeier I understand your objections. And of course it's not an obvious lack of functionality, but just a lack of convenience for the main (or at least my) use case. How you want to proceed here is of course entirely your choice. For me personally, it doesn't matter whether the functionality is included in the library, since otherwise I can simply work with a fork of mine that includes it. If it suits your needs and you want this implemented, I can support you in doing so. But, again, don't do it for me.

**Comment by hnorkowski** [comment]
The idea was to use [this function](https://github.com/FraunhoferISST/TREND/blob/main/watermarker/src/commonMain/kotlin/Watermarker.kt#L192) to directly extract `TextWatermarks` which automatically parses the data as text and makes it accessible [here](https://github.com/FraunhoferISST/TREND/blob/main/watermarker/src/commonMain/kotlin/watermarks/TextWatermark.kt#L34).

**Comment by gemdav** [comment]
@hnorkowski I am searching for a way to extract Trendmark objects from a cover that enable me to get the watermark content as a string and still feature the neat features of Trendmarks, above all their validation. Correct me if I am wrong, but how I see it is that, using your approach, I would have to extract the watermarks from the cover twice: once as TextWatermark objects and once as Trendmark objects.

**Comment by hnorkowski** [comment]
> @hnorkowski I am searching for a way to extract Trendmark objects from a cover that enable me to get the watermark content as a string and still feature the neat features of Trendmarks, above all their validation. Correct me if I am wrong, but how I see it is that, using your approach, I would have to extract the watermarks from the cover twice: once as TextWatermark objects and once as Trendmark objects.

I think I would require some more details about what features you are using of the `Trendmark` which are not available in the `TextWatermark`. 

But maybe some general information are helpful: The architecture of the watermarks is layered:
- at the base is the `Watermark` which does not do anything with the bytes that got watermarked
- on top of that there is the `Trendmark` which defines some structure to the bytes to provide some features like format tags and sanity checks
- on on top of the trendmark there is the `TextWatermark` which adds specific capabilities to handle `Trendmarks` which text as content.

This means that when you have a `TextWatermark` its on top of a `Trendmark` and you can always convert between these two types if you ever require functions that are only available in one of them. E.g. you can see [here](https://github.com/FraunhoferISST/TREND/blob/main/watermarker/src/commonMain/kotlin/watermarks/TextWatermark.kt#L240) that to parse a `Watermark` into a `TextWatermark` it first is converted to a `Trendmark`.

But for your case if you need a functionality of `Trendmark` that cannot be re-exported by `TextWatermark` you could just get them all as `Trendmark` and after you did what ever you need to do with them you can convert them to `TextWatermarks` one-by-one using the `TextWatermark.fromTrendmark` function (or write an extension function for that) or just convert them all in one step using [this](https://github.com/FraunhoferISST/TREND/blob/main/watermarker/src/commonMain/kotlin/watermarks/TextWatermark.kt#L203) function.

Sorry for the late answer, hope this helps :)

**Comment by gemdav** [comment]
Unfortunately, the `TextWatermark.fromTrendmark` function (which is also used by the `Result<List<Trendmark>>.toTextWatermarks` function) does not support most of the Trendmark types. As I am not too involved in the development of the library I do not know whether this is just a temporary issue or built to last. 

https://github.com/FraunhoferISST/TREND/blob/d0634e1cb2fd723f52bb7097c5834965cf85e943/watermarker/src/commonMain/kotlin/watermarks/TextWatermark.kt#L101-L120

If this limitation is about to be removed, then I agree that, considering the current architecture of the library, this functionality proposed here should not be implemented. But if the limitation persists, then the solution you propose does not work for most of the Trendmark types and thus for many use cases.

**Comment by mhellmeier** [comment]
You are right, @gemdav, that some Trendmark implementations are missing. This should be fixed with #134.
