### ISSUE TITLE
CompressedSizedCRC32Trendmark missing Trendmark.Compressed Implementation

### ISSUE THREAD

**Issue by Schiphorst-ISST** [FraunhoferISST/Innamark#128]
# 🐞 Bug Report

## Describe the Bug
The CompressedSizedCRC32Trendmark (in watermarker/src/commonMain/kotlin/watermarks/Trendmark.kt) implements Trendmark(content), Trendmark.sized, Trendmark.Checksum but not Trendmark.Compressed.

## To Reproduce
1. Attempt to Cast a CompressedSizedCRC32Trendmark to Trendmark.Compressed (which works with all other Compressed Trendmarks)
2. java.lang.ClassCastExecption is thrown

## Expected Behavior
Casting CompressedSizedCRC32Trendmark to Trendmark.Compressed should be possible without issue

## System Information
 - Component: watermarker
 - Runtime: java 17 on ubuntu 24.04 LTS

**Comment by mhellmeier** [comment]
Furthermore, the `TextWatermark` class only implements the `compressed` and `sized` targets:
https://github.com/FraunhoferISST/TREND/blob/d0634e1cb2fd723f52bb7097c5834965cf85e943/watermarker/src/commonMain/kotlin/watermarks/TextWatermark.kt#L35

This can also be extended to support CRC32 and SHA3.
