### ISSUE TITLE
Increase convenience of the StartEndSeparatorChars separator strategy

### ISSUE THREAD

**Issue by gemdav** [FraunhoferISST/Innamark#45]
# 🚀 Feature Request

## Current Problem

The `StartEndSeparatorChars` separator strategy is not very convenient to use as the users of the library have to define the start- and end-separators themselves.

https://github.com/FraunhoferISST/TREND/blob/261b35c53097a4e37981f1a11be5c98fa4c750c6/watermarker/src/commonMain/kotlin/fileWatermarker/TextWatermarker.kt#L31

## Proposed Solution

**It would be nice to have default start- end end-separator characters defined**, such that the users of the library do not have to look for promising white space charaters themselves. I am thinking of something like two additional constants in the `DefaultTranscoding` object (there is already one for the `SingleSeparatorChar` strategy).

https://github.com/FraunhoferISST/TREND/blob/261b35c53097a4e37981f1a11be5c98fa4c750c6/watermarker/src/commonMain/kotlin/fileWatermarker/TextWatermarker.kt#L56

Possible extension:

```Kotlin
const val SEPARATOR_CHAR = '\u2004' // Three-per-em space

const val START_SEPARATOR_CHAR = '\u2004' // Three-per-em space
const val END_SEPARATOR_CHAR = '\u2005' // Four-per-em space (or whatever replaces normal white spaces best)
```

That's where, in my opinion, a small refactoring of the code would also contribute to its convenience. The `SingleSeparatorChar` and `StartEndSeparatorChars` should get default arguments in their constructor in order to easily get a default instance of these classes.

#### Why choose the `StartEndSeparatorChars` strategy at all?

Adding watermarks to a text using the default `SingleSeparatorChar` separator strategy is relatively inflexible in use cases like watermarking of mails or collaboratively created document where there are mutliple parties that all might want to add their own watermark: When two watermarked texts are merged, the last repetition (fragment) of the first watermark and the first repetition of the second watermark "blur" into one another, as the last repetition of the first watermark most likely does not perfectly end on its separation character.

For example when reading the watermark from this merged text ...

```bash
# Contains (complete) watermarks ["AA", "AA"] + fragment
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
# Contains (complete) watermarks ["BB", "BB"] + fragment
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
```

... it does not result in `["AA", "AA", "BB", "BB"]` but in `["AA", "AA", "A\t\t\u0001", "BB"]`. This is due to the last repetition of the first watermark being fragmented. It does not conclude with a separation character and is thus interpreted as part of the next watermark.

Now one could propose a solution to this problem that includes removing the watermarks from both texts and re-adding them to the whole text  in a combined way (e.g. `"AA;BB"`, but in my eyes that procedure has 2 main disadvatages:

   1. The information on which watermark belongs to which part of the text gets lost
   2. The watermark becomes less robust as removals of characters threaten the integrity of the watermark-combination and thus all watermarks and not only one.

That's where the `StartEndSeparatorChars` strategy comes in handy, as it prevents watermarks from blurring into one another in the first place.

**Comment by mhellmeier** [comment]
Having a default start and end character doesn't work since the current set of chars (watermarking alphabet) is carefully selected and evaluated.
Another solution would be to start every watermark with the current separator character.

**Comment by hnorkowski** [comment]
The underlying problem here is that watermarking a text that already contains a watermark will cause the last incomplete watermark and the first new to merge because there is no separator char between them. To fix this issue we decided to prepend every watermark with the separator char instead of prepending it.
