### ISSUE TITLE
JS: `TrendmarkBuilder.finish()` gets renamed

### ISSUE THREAD

**Issue by hnorkowski** [FraunhoferISST/Innamark#76]
# 🐞 Bug Report

## Describe the Bug

In JavaScript the `finish()` method `TextWatermark` class in JavaScript the finish method is renamed to `pl()`.

## To Reproduce
1. open `TREND/samples/plain_js/plain_js_minimal_example.html` in a browser
2. open the console
3. try executing `watermark.finish()`
5. try executing `watermark.pl()` instead
6. See generated `Trendmark`

## Expected Behavior

The functions should be generated with the same name defined in the `TrendmarkBuilder` interface and the class `TextWatermar`

## Additional Context

It should be check if other functions are renamed as well.

**Comment by gemdav** [comment]
I managed to have the compiler name the function correctly using the `@JsName` annotation (see [here](https://github.com/gemdav/TREND/commit/01f587267854c5ee08de9b72202f875887023910)).

This is probably not prettiest approach, but if no other is found, it can be used as a fallback.

Also, I have no clue why the copiler mangles the name without the annotation or why it works with the annotation.

**Comment by hnorkowski** [comment]
I have found the cause:
I did not add a `@JsExport` to the `TrendmarkBuilder` interface. The reason for that was that the compiler / IntelliSense complained that interfaces are not supported in JS and therefore should not be exported. However, when exporting the interface the do not get mangled.
