### ISSUE TITLE
Add functionality to only compress a watermark if the compression actually decreases the size

### ISSUE THREAD

**Issue by gemdav** [FraunhoferISST/Innamark#98]
# 🚀 Feature Request

## Current Problem

Currently, the user of the TREND library has to decide whether he wants to use a compressed or uncompressed watermark. Usually, uncompressed watermarks are chosen in situations where the watermark size plays an important role and needs to be kept as small as possbile. However, especially for short texts, a compression does not always decrease the size of a text but can also increase it, which is usually undesired.

## Proposed Solution

It should be convenient to use compressed watermarks in such way that they are only compressed if a compression acutally decreases the size of the watermark. If it does not, the raw watermark is used.

In my opinion, there are two suitable options to address this issue:

#### [1] The "convenience function" option

One way to address this new feature could be to create a new a convenience function, either in the `TextWatermarker` or the `Watermarker` class, that takes a string or bytes and creates a `Trendmark` from it. Whether the `Trendmark` is compressed or not is decided based on the size.

This option does not require many changes in the existing code but requires users that want to use this feature to rely on the new convenience function which might not be their favored option to interact with the library.

#### [2] The "fundamental decision on compressed watermarks" option

The logic for this feature can also be directly implemented into the `Compressed[*]Trendmark` classes, such that the content of these Trendmarks is only deflated if the compression actually decreases their size. The question and therefore design decision at hand is whether compressed watermarks should always be compressed or always be as small as possible. Of course this option could be paired with an `enforceCompression` parameter that, if set to `true`, specifies that the content of the watemark should be compressed regardless of a possibly increased size.

**Comment by gemdav** [comment]
@mhellmeier please let me know which of the provided options you prefer or if you see any other ones.

**Comment by mhellmeier** [comment]
Regarding your question:
> The question and therefore design decision at hand is whether compressed watermarks should always be compressed or always be as small as possible

If I decide to use a compressed watermark, I also expect to _always_ get a compressed watermark, even if the compression makes the actual watermark bigger.

I think Option [2] won't work because the information if the compression algorithm is used is not shipped within the watermark. Therefore, the receiving part must identify whether or not it needs to decode the watermark.

Therefore, I think Option [1] sounds best.
